apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-server
    language: python
  name: http-server
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-server
      language: python
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: http-server
        language: python
    spec:
      containers:
      - image: gcr.io/fourth-ability-322319/github.com/mikemike111997/http-service
        imagePullPolicy: IfNotPresent
        name: http-service
      restartPolicy: Always

