apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: http-server
    language: python
  name: http-server
  namespace: default
  uid: 71ee9902-83e1-4706-aebf-46fd4ad82c26
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: http-server
      language: python
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: http-server
        language: python
    spec:
      containers:
      - image: gcr.io/fourth-ability-322319/github.com/mikemike111997/http-service@sha256:0ac1fe3008a7a75fcdd09fd1bee0b87e4f3bc805017438d81e4174ec18dff451
        imagePullPolicy: IfNotPresent
        name: http-service-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
